repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v3.2.0"
  hooks:
    - id: check-merge-conflict
      exclude: third-party
    - id: debug-statements
      exclude: third-party

- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--line-length=88, --target-version=py37]
      exclude: third-party

    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [python]
      args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
      exclude: third-party

    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [python]
      args: [--py37-plus]
      exclude: third-party