vk:
  # Access token for an authorized application,
  # e.g. from https://vkhost.github.io/
  token: 'TOKEN'
  app-id: 1234567
tg_bot:
  # Bot token from @BotFather
  bot-token: 'BOT-TOKEN'

  # ID of user to forward the messages to
  # One can find it out by writing to @userinfobot
  user-id: 1234567890

  # NOT USING PROXY
  proxy-url: ~

  # TO USE PROXY, SET THE TYPE
  # (HTTP, SOCKS5, SOCKS4), HOST AND PORT
  # proxy-url: "socks5://127.0.0.1:12345"
